// Generated by `wit-bindgen` 0.25.0. DO NOT EDIT!
#include "bindings.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `example`

__attribute__((__weak__, __export_name__("cabi_post_hello-world")))
void __wasm_export_bindings_hello_world_post_return(uint8_t * arg0) {
  if ((*((size_t*) (arg0 + 4))) > 0) {
    free(*((uint8_t **) (arg0 + 0)));
  }
}

// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void bindings_string_set(bindings_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void bindings_string_dup(bindings_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void bindings_string_free(bindings_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(4)))
static uint8_t RET_AREA[8];

__attribute__((__export_name__("hello-world")))
uint8_t * __wasm_export_bindings_hello_world(void) {
  bindings_string_t ret;
  bindings_hello_world(&ret);
  uint8_t *ptr = (uint8_t *) &RET_AREA;
  *((size_t*)(ptr + 4)) = (ret).len;
  *((uint8_t **)(ptr + 0)) = (uint8_t *) (ret).ptr;
  return ptr;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_bindings(void);
void __component_type_object_force_link_bindings_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_bindings();
}
